### PR TITLE
Added Eso reader and fixed multiple issues

### LINKED ISSUE #84: Add ReadResults method to process results from simulation
#### Description:

Either handling the `*.eso` file or the converted CSV file (preferably the `*.eso` file as that prevents the need to duplicate the values in a different format on output or pass the `-x` argument to the simulation cmd), this method would read in the simulated results from the EnergyPlus run and output something that looks like this:
image

### LINKED ISSUE #86: Annual simulation running regardless of IDF setup
#### Description:

Inclusion of "-a" in cmd string forces annual simulation. Remove this.

### LINKED ISSUE #87: Prevent IDF simulation automatically
#### Description:

Add a "run" bool to the Compute IDF component to prevent automatic simulation without user go-ahead.

### LINKED ISSUE #88: Remove incorrect namespaces
#### Description:

A couple of namespaces leftover from copied code included. Plus a few overrides required where Name is an attribute used by IEnergyPlusClass as essential for that component to function in conjunction with the Order attribute for correct serialisation. See VisualStudio Warnings for the exact methods to change.

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #84
Closes #86
Closes #87 
Closes #88

See issue descriptions.

### CODE REVIEW

File: EnergyPlus_Engine/Compute/SimulateIDF.cs [hunk 1]
```diff
@@ -27,17 +27,18 @@
...
         [Description("Run an IDF file")]
         [Input("energyPlusSettings", "EnergyPlusSettings object")]
         [Input("idfFile", "EnergyPlus IDF file to simulate")]
+        [Input("run", "Set to \"True\" to run simulation")]
         [Output("success", "True if command has been run sucessfully (subject to program being called correctly returning an Exit Code)")]
-        public static bool SimulateIDF(EnergyPlusSettings energyPlusSettings, string idfFile)
+        public static bool SimulateIDF(EnergyPlusSettings energyPlusSettings, string idfFile, bool run = false)
         {
-            string formatString = "{0} -a -r -x -d {1} -p {2} -w {3} {4}";
+            string formatString = "{0} -r -x -d {1} -p {2} -w {3} {4}";
```
Comment (FraserGreenroyd) [inline EnergyPlus_Engine/Compute/SimulateIDF.cs:41]: I suspect it might be useful to make use of the `run` argument somewhere? I'd add

```
if(!run)
    return false;
```

Above this line?

File: EnergyPlus_Engine/Query/ReadESO.cs [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+                }
+
+                double value = Double.Parse(kvPair[1]);
+                resultsValues[key].Add(value);
+                
+            }
+
+            esoFile.ResultsAttribute = resultsAtrributes;
+            esoFile.ResultsObjects = resultsKeys;
+            esoFile.ResultsValues = resultsValues.Values.ToList();
```
Comment (FraserGreenroyd) [inline EnergyPlus_Engine/Query/ReadESO.cs:102]: I suspect this should probably be done by the adapter, but happy to leave it as is for now to kick start development and we can look at the right method next week

File: EnergyPlus_oM/EsoFile.cs [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+using BH.oM.Base;
+using BH.oM.Reflection;
+using System;
+using System.Collections.Generic;
+using System.ComponentModel;
+
+namespace BH.oM.EnergyPlus
+{
+    public class ESOFile : BHoMObject
```
Comment (FraserGreenroyd) [inline EnergyPlus_oM/EsoFile.cs:31]: This will definitely benefit from being a result object I think, but something for us to discuss in more detail I think.

For someone who says `I think` a lot in that sentence, I didn't actually do as much as I would like...

File: EnergyPlus_Engine/Compute/SimulateIDF.cs (hunk 1 above)
Comment (tg359) [reply EnergyPlus_Engine/Compute/SimulateIDF.cs:41]: Haha, that's a bit of an omission isn't it! That's been dealt with now.

On the subject of running executables with arguments, I'm wondering if there's a [better way to handle this](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.arguments?view=netcore-3.1) as it's becoming more common. A discussion for another place maybe?

**Comment by cskinnerBH** [comment]
Looks to be working as intended! 

Also - thanks for adding the toggle to the run IDF component!!!

image
